export default [
  {
    title: 'Work Anywhere',
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    backgroundColor: 'rgba(2,100,188,.8)',
    gradients: ['rgba(28, 162, 98, .8)', 'rgba(66, 184, 146, .8)'],
    image: 'https://supermachine.files.wordpress.com/2016/09/sms_hubbato_blog05.jpg?w=1200',
    imageFull: 'https://supermachine.files.wordpress.com/2016/09/sms_hubbato_blog05.jpg?w=1200',
    imageBlur: 'https://unsplash.it/1200/1200?image=674&blur',
    icon : 'globe',
    iconImage: require('@assets/images/flower-pot.png'),
    img: require('@assets/images/airbaloon.png'),
  },
  {
    title: 'Work for $1/hour',
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    backgroundColor: 'rgba(97,180,9,.8)',
    gradients: ['rgba(14, 84, 194, 1)', 'rgba(209, 67, 141, .8)'],
    image: 'http://2017.baltimoreinnovationweek.com/thumbnail/622/1200x1200',
    imageFull: 'http://2017.baltimoreinnovationweek.com/thumbnail/622/1200x1200',
    imageBlur: 'https://unsplash.it/1200/1200?image=668&blur',
    icon : 'diamond',
    iconImage: require('@assets/images/footprints.png'),
    img: require('@assets/images/boat.png'),
  },
  {
    title: 'Coworking at restaurants',
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    backgroundColor: 'rgba(83,103,153, .8)',
    gradients: ['rgba(60, 206, 207, .8)', 'rgba(51, 19, 104, .8)'],
    image: 'https://www.smart-magazine.com/content/uploads/2017/03/Taverna-co-work.jpg',
    imageFull: 'https://www.smart-magazine.com/content/uploads/2017/03/Taverna-co-work.jpg',
    imageBlur: 'https://unsplash.it/1200/1200?image=1083&blur',
    icon : 'settings',
    iconImage: require('@assets/images/happy-sun.png'),
    img: require('@assets/images/egypt.png'),
  },
    {
    title: 'Coworking at restaurants',
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    backgroundColor: 'rgba(83,103,153, .8)',
    gradients: ['rgba(60, 206, 207, .8)', 'rgba(51, 19, 104, .8)'],
    image: 'https://www.smart-magazine.com/content/uploads/2017/03/Taverna-co-work.jpg',
    imageFull: 'https://www.smart-magazine.com/content/uploads/2017/03/Taverna-co-work.jpg',
    imageBlur: 'https://unsplash.it/1200/1200?image=1083&blur',
    icon : 'settings',
    iconImage: require('@assets/images/happy-sun.png'),
    img: require('@assets/images/egypt.png'),
  },
]
